name: CI Hospital Pipeline

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    # SERVICIO DE BASE DE DATOS (Con espera de seguridad)
    services:
      mongodb:
        image: mongo:5.0
        ports:
          - 27017:27017
        # Esto es vital: Espera a que la BD responda antes de seguir
        options: >-
          --health-cmd mongo
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    # PASO 1: Obtener el código (Actualizado a v4)
    - uses: actions/checkout@v4
    
    # PASO 2: Instalar Java 17 (Actualizado a v4)
    - name: Configurar Java 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    # PASO 3: Ejecutar las pruebas (JUnit + JaCoCo)
    - name: Ejecutar Tests
      run: mvn clean test
      
    # PASO 4: Guardar el reporte (Actualizado a v4)
    - name: Subir Reporte Cobertura
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: reporte-cobertura
        path: target/site/jacoco/
